[package]
name = "rust-grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

